version: '3'

services:
  app:
    container_name: app-edu-portfolio
    image: app-edu-portfolio
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    command: >
      sh -c "yarn install && yarn start"
